output: json

location:
  lat: 45.5902
  lon: -120.6707

metrics:
  - rmse

prepare:
  - trim:
      low: -1000.0
      high: 1000.0

left:
  name: d01
  path: /scratch/cphillip/d01
  format: wrf_netcdf
  var: WSPD80

right:
  - name: d02
    path: /scratch/cphillip/d02
    format: wrf_netcdf
    var: WSPD80
