location:
  lat: 45.5902
  lon: -120.6707

metrics:
  - rmse

left:
  path: /scratch/cphillip/d01
  format: netcdf
  var: WSPD80

right:
  - path: /scratch/cphillip/d02
    format: netcdf
    var: WSPD80