location:
  lat: 45.5902
  lon: -120.6707

prepare:
  - trim:
      lower: -1000.0
      upper: 1000.0
  - linear_interp:
      n: 23

metrics:
  - rmse

left:
  name: d01
  path: /scratch/cphillip/d01
  format: wrf_netcdf
  var: WSPD80

right:
  - name: d02
    path: /scratch/cphillip/d02
    format: wrf_netcdf
    var: WSPD80
