# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 45.57451
  lon: -120.74734

time:
  window:
    # validation period start time
    lower: 2016-09-23 12:00:00
    # validation period end time
    upper: 2016-09-25 12:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 40
    - 80
    - 120
  height_units: m

# baseline dataset
base:
  name: sodar
  # data directory
  path: data/mw_data_sodar
  # name of data processing function
  format: sodar_netcdf
  # names of variables in data to validate
  var: wind_speed
  # target variable name to be displayed
  target_var: sodar_ws
  # data frequency in minutes
  freq: 10
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: wrf
    # data directory
    path: data/mw_data_wrf
    # name of data processing function
    format: wrf_netcdf
    # names of variables in data to validate
    var: 
      - u
      - v
    # target variable name to be displayed
    target_var: wrf_ws
    # data frequency in minutes
    freq: 5
    # flag value
    flag: 999

# plotting 
plot: 
  # variable name to be displayed
  var: wind speed
  # variable units
  units: ms-1