# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 45.57451
  lon: -120.74734

time:
  window:
    # validation period start time
    lower: 2016-09-23 12:00:00
    # validation period end time
    upper: 2016-09-25 12:00:00
  # trim: left # can be left or right

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - bias
  - bias_pct
  - mae
  - mae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 40
    # - 80
    # - 120

# baseline dataset
base:
  name: sodar

  # data directory
  # path: data/mw_data_sodar

  # add sodar.z06.b0.20160924.170000.txt2.a2e.nc, sodar.z06.b0.20160924.171001.txt2.a2e.nc
  # path: data/test_sodar_dup
  
  # delete sodar.z06.b0.20160924.170000.txt.a2e.nc
  # path: data/test_sodar_gap
  
  # duplicate & missing data
  # path: data/test_sodar_dupgap 

  # duplicate & missing data, miss first 12 hours
  path: data/test_sodar_shortdupgap 
  
  format: sodar_netcdf
  # variables to validate
  var: wind_speed
  # target variable name to output
  target_var: sodar_ws
  # data frequency in minutes
  freq: 10
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: wrf
    # data directory
    path: data/mw_data_wrf
    format: wrf_netcdf
    # variables to validate
    var: 
      - u
      - v
    # target variable name to output
    target_var: wrf_ws
    # data frequency in minutes
    freq: 5
    # flag value
    flag: 999