location:
  lat: 45.5902
  lon: -120.6707

prepare:
  - trim:
      lower: -1000.0
      upper: 1000.0
  - linear_interp:
      #n: 23
      period: 500

time:
  window:
    lower: 2016-03-07 06:00:00
    upper: 2016-03-07 10:00:00
  trim: left # can be left or right

metrics:
  - rmse

left:
  name: d01
  path: /scratch/cphillip/d01
  format: wrf_netcdf
  var: WSPD80

right:
  - name: d02
    path: /scratch/cphillip/d02
    format: wrf_netcdf
    var: WSPD80
