location:
  lat: 45.5902
  lon: -120.6707

metrics:
  - rmse

left:
  name: d01
  path: /scratch/cphillip/d01
  format: netcdf
  var: WSPD80

right:
  - name: d02
    path: /scratch/cphillip/d02
    format: netcdf
    var: WSPD80

cache: /
