location:
  lat: 46.5902
  lon: -120.6707

prepare:
  - trim:
      lower: -1000.0
      upper: 1000.0
  - linear_interp:
      #n: 23
      period: 500

time:
  window:
    lower: 2016-03-07 06:00:00
    upper: 2016-03-07 12:00:00
  trim: left # can be left or right

metrics:
  - rmse
  - bias
  - bias_pct
  - mae
  - mae_pct

left:
  name: ex1
  path: data/ex1
  format: wrf_netcdf
  var: WSPD80

right:
  - name: ex2
    path: data/ex2
    format: wrf_netcdf
    var: WSPD80
