location:
  lat: 45.57451
  lon: -120.74734

prepare:
  - trim:
      lower: -1000.0
      upper: 1000.0
  - linear_interp:
      #n: 23
      period: 300 # every 300 second, according to WRF output's resolution

time:
  window:
    lower: 2016-09-23 12:00:00
    upper: 2016-09-25 12:00:00
  trim: left # can be left or right

metrics:
  - rmse
  - bias
  - bias_pct
  - mae
  - mae_pct

left:
  name: wrf
  path: data/mw_data_wrf
  #path: data/testing1
  format: wrf_netcdf
  var: 
    - u
    - v

right:
  - name: sodar
    path: data/mw_data_sodar
    #path: data/testing2
    format: sodar_netcdf
    var: wind_speed
